### ISSUE TITLE
ImportError: No module named cryptography

### ISSUE THREAD

**Issue by ftiff** [sheagcraig/python-jss#61]
JSSImporter 0.5.1 was installed by AutoPkgr

Since then I get this error when running `autopkg`:
```
$ autopkg 
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 36, in <module>
    import autopkglib.github
  File "/Library/AutoPkg/autopkglib/__init__.py", line 629, in <module>
    import_processors()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 532, in import_processors
    mydirname + '.' + name, fromlist=[name]), name)
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 28, in <module>
    import jss
  File "/Library/Python/2.7/site-packages/python_jss-1.5.0-py2.7.egg/jss/__init__.py", line 60, in <module>
    from .jamf_software_server import JSS
  File "/Library/Python/2.7/site-packages/python_jss-1.5.0-py2.7.egg/jss/jamf_software_server.py", line 37, in <module>
    from .tlsadapter import TLSAdapter
  File "/Library/Python/2.7/site-packages/python_jss-1.5.0-py2.7.egg/jss/tlsadapter.py", line 26, in <module>
    from requests.packages.urllib3.contrib import pyopenssl
  File "/Library/Python/2.7/site-packages/urllib3-1.22-py2.7.egg/urllib3/contrib/pyopenssl.py", line 47, in <module>
    from cryptography import x509
ImportError: No module named cryptography
```

**Comment by ftiff** [comment]
`sudo easy_install cryptography` fails with:
```
build/temp.macosx-10.12-intel-2.7/_openssl.c:434:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
error: Setup script exited with error: command 'cc' failed with exit status 1
```
running `easy_install pip` then `pip install cryptography` does the trick.

**Comment by ftiff** [comment]
ok I get the same error because of `from jss import __version__` it seem

**Comment by sheagcraig** [comment]
The testing branch uses curl by default for networking, so you won't have to worry about any python packages.
